mod core;
mod file_ops;
mod commands;
mod web;
mod human;
mod code_analysis;
mod git;
mod agents;
mod test_coverage;
mod background;
mod browser;
mod self_improvement;
mod memory;
mod workspace;

pub use core::{ToolResult, LlmAction, TelegramConfig, dispatch, resolve, str_arg, take_arg, chrono_now};
pub use file_ops::{read_file, write_file, str_replace, list_dir, find_files, search_in_files};
pub use commands::run_command;
pub use web::{fetch_url, web_search, github_api};
pub use human::{ask_human, notify};
pub use code_analysis::{get_symbols, outline, get_signature, find_references};
pub use git::{git_status, git_commit, git_log, git_stash, git_pull, git_push};
pub use agents::{spawn_agent, spawn_agents};
pub use test_coverage::test_coverage;
pub use background::{run_background, process_status, process_kill, process_list};
pub use browser::{browser_screenshot, browser_get_text, browser_action, browser_navigate};
pub use self_improvement::{tool_request, capability_gap};
pub use memory::{memory_read, memory_write};
pub use workspace::{diff_repo, tree};
